# -*- coding: utf-8 -*-
"""KassYolo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zvGeeimXpWyLG7Ie0GN8pK5Y_mWChE8S

# Video detection with ImageAI and YOLOv3

**ImageAI** provided very powerful yet easy to use classes and functions to perform Video Object Detection and Tracking and Video analysis. 

**ImageAI** allows you to perform all of these with state-of-the-art deep learning algorithms like RetinaNet, YOLOv3 and TinyYOLOv3. 

With ImageAI you can run detection tasks and analyse videos and live-video feeds from device cameras and IP cameras. 

In this tutorial we will implement a case study using YOLOv3 over a stored video. The code is inspired by the [ImageAI documentation](https://imageai.readthedocs.io/en/latest/video/index.html)

## Install & Load the resources
"""

!pip3 install https://github.com/OlafenwaMoses/ImageAI/releases/download/2.0.2/imageai-2.0.2-py3-none-any.whl
!pip install -q opencv-python
!pip install -q pillow
!pip install cython pillow>=7.0.0 numpy>=1.18.1 opencv-python>=4.1.2 torch>=1.9.0 --extra-index-url https://download.pytorch.org/whl/cpu torchvision>=0.10.0 --extra-index-url https://download.pytorch.org/whl/cpu pytest==7.1.3 tqdm==4.64.1 scipy>=1.7.3 matplotlib>=3.4.3 mock==4.0.3

!pip install imageai --upgrade

from imageai.Detection import VideoObjectDetection
import matplotlib as plt
import tensorflow as tf
import numpy as np
import scipy
import keras
import h5py

"""## Create an instance of the VideoObjectDetection"""

detector = VideoObjectDetection()

"""## YOLO v3

This function sets the model type of the object detection instance we created to the YOLOv3 model, which means we will be performing our object detection tasks using the pre-trained “YOLOv3” model.

We can also set the model either to RetinaNet with **.setModelTypeAsRetinaNet()** or to TinyYOLOv3 with **.setModelTypeAsTinyYOLOv3()**
"""

detector.setModelTypeAsYOLOv3()

"""## Mount the drive to import yolov3.pt and the video

> Indented block


"""

from google.colab import drive
drive.mount('/content/gdrive')

!ls '/content/gdrive/My Drive/Colab Notebooks/yolo/data'

"""## The model file
This function accepts a string which must be the path to the model file we downloaded
"""

detector.setModelPath("/content/gdrive/My Drive/Colab Notebooks/yolo/data/yolov3.pt")

"""## Load the model
This function loads the model from the path we specified in the function call above into our object detection instance

"""

detector.loadModel()

"""## Detect Objects From Video
This is the function that performs object detecttion on a video file or video live-feed after the model has been loaded into the instance we created.
"""

video_path = detector.detectObjectsFromVideo(input_file_path="/content/gdrive/My Drive/Colab Notebooks/yolo/data/video.mp4",
                                output_file_path="/content/gdrive/My Drive/Colab Notebooks/yolo/data/video_output",
                                frames_per_second=29, log_progress=True)

"""– *parameter* **input_file_path** (required if you did not set camera_input) : This refers to the path to the video file you want to detect.

— *parameter* **output_file_path** (required if you did not set save_detected_video = False) : This refers to the path to which the detected video will be saved. By default, this functionsaves video .avi format.

– *parameter* **frames_per_second** (optional , but recommended) : This parameters allows you to set your desired frames per second for the detected video that will be saved. The default value is 20 but we recommend you set the value that suits your video or camera live-feed.

— *parameter* **log_progress** (optional) : Setting this parameter to True shows the progress of the video or live-feed as it is detected in the CLI. It will report every frame detected as it progresses. The default value is False.

— *parameter* **camera_input** (optional) : This parameter can be set in replacement of the input_file_path if you want to detect objects in the live-feed of a camera.
"""

!ls '/content/gdrive/My Drive/Colab Notebooks/yolo/data'